import React from 'react';
const columns = [
  { name: 'ID', uid: 'id' },
  { name: 'Name', uid: 'name' },
  { name: 'Shift', uid: 'shift' },
  { name: 'Employee Type', uid: 'employeeType' },
  { name: 'Contact No', uid: 'contactNo' },
  { name: 'Mail Id', uid: 'email' },
];

const users = [
  {
    name: 'Tony Reichert',
    shift: 'Day Shift',
    id: 1,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony.reichert@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 2,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'reichert@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 3,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony@example.com',
  },
  {
    name: 'Tony Reichert',
    shift: 'Day Shift',
    id: 4,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony.reichert@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 5,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'reichert@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 6,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony@example.com',
  },
  {
    name: 'Tony Reichert',
    shift: 'Day Shift',
    id: 1,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony.reichert@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 2,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'reichert@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 3,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 3,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 3,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 3,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony@example.com',
  },
  {
    name: 'Reichert',
    shift: 'Day Shift',
    id: 3,
    employeeType: 'Permanent',
    contactNo: '+911234567890',
    email: 'tony@example.com',
  },
];

export { columns, users };
